services:
  ppt-watcher:
    image: auto-ppt-to-pdf
    container_name: auto-ppt-to-pdf
    volumes:
      - ~/Downloads:/mnt/downloads
    privileged: true
    restart: unless-stopped
    ports:
      - "8000:8000" 